import "../styles/globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import type { AppProps } from "next/app";
import { Roboto } from "next/font/google";
import { WagmiConfig, configureChains, createConfig } from "wagmi";
import { publicProvider } from "wagmi/providers/public";
import { alchemyProvider } from "wagmi/providers/alchemy";
import { jsonRpcProvider } from "wagmi/providers/jsonRpc";
import { RainbowKitProvider } from "@rainbow-me/rainbowkit";
import { Toaster } from "react-hot-toast";
import Head from "next/head";
import { Provider } from "jotai";
// @ts-ignore
import NoSSR from 'react-no-ssr';
import Page from "@/components/Page";
import { SUPPORTED_NETWORKS } from "@/lib/connectors";
import { connectorsForWallets } from '@rainbow-me/rainbowkit';
import {
  injectedWallet,
  rainbowWallet,
  metaMaskWallet,
  coinbaseWallet,
  walletConnectWallet,
  coin98Wallet,
} from '@rainbow-me/rainbowkit/wallets';

const { chains, publicClient } = configureChains(SUPPORTED_NETWORKS, [
  alchemyProvider({
    apiKey: process.env.NEXT_PUBLIC_ALCHEMY_API_KEY as string,
  }),
  jsonRpcProvider({ rpc: (chain) => ({ http: chain.rpcUrls.default.http[0] }) })],
  {
    pollingInterval: 7_000,
    stallTimeout: 5_000, // time to change to another RPC if failed
  }
);

const connectors = connectorsForWallets([
  {
    groupName: 'Suggested',
    wallets: [
      injectedWallet({ chains }),
      rainbowWallet({ projectId:'9b83e8f348c7515d3f94d83f95a05749', chains }),
      metaMaskWallet({ projectId:'9b83e8f348c7515d3f94d83f95a05749', chains }),
    ],
  },
  {
    groupName: 'Others',
    wallets: [
      coinbaseWallet({ chains, appName: 'VaultCraft' }),
      walletConnectWallet({ projectId:'9b83e8f348c7515d3f94d83f95a05749', chains }),
      coin98Wallet({ projectId:'9b83e8f348c7515d3f94d83f95a05749', chains })
    ]

  }
]);

const config = createConfig({
  autoConnect: true,
  connectors,
  publicClient
})

const nextFont = Roboto({
  weight: ["400", "700", "900"],
  subsets: [],
});


export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>VCI - Creator Interface</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={nextFont.className}>
        <style
          dangerouslySetInnerHTML={{
            __html: `
            :root [data-rk] {
              --rk-radii-modal: 1rem;
            }
            [data-rk] * {
              font-family: ${nextFont.style.fontFamily} !important;
            }
          `,
          }}
        />
        <Toaster />
        <WagmiConfig config={config}>
          <RainbowKitProvider chains={chains} modalSize="compact">
            <NoSSR>
              <Provider>
                <Page>
                  <Component {...pageProps} />
                </Page>
              </Provider>
            </NoSSR>
          </RainbowKitProvider>
        </WagmiConfig>
      </main>
    </>
  );
}
